# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/h4kcrun/Repos/QuAK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/h4kcrun/Repos/QuAK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/h4kcrun/Repos/QuAK/CMakeFiles /Users/h4kcrun/Repos/QuAK//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/h4kcrun/Repos/QuAK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named quakbin

# Build rule for target.
quakbin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quakbin
.PHONY : quakbin

# fast build rule for target.
quakbin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakbin.dir/build.make CMakeFiles/quakbin.dir/build
.PHONY : quakbin/fast

#=============================================================================
# Target rules for targets named quak

# Build rule for target.
quak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quak
.PHONY : quak

# fast build rule for target.
quak/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quak.dir/build.make src/CMakeFiles/quak.dir/build
.PHONY : quak/fast

#=============================================================================
# Target rules for targets named quak-private

# Build rule for target.
quak-private: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quak-private
.PHONY : quak-private

# fast build rule for target.
quak-private/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quak-private.dir/build.make src/CMakeFiles/quak-private.dir/build
.PHONY : quak-private/fast

#=============================================================================
# Target rules for targets named quakso

# Build rule for target.
quakso: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quakso
.PHONY : quakso

# fast build rule for target.
quakso/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quakso.dir/build.make src/CMakeFiles/quakso.dir/build
.PHONY : quakso/fast

#=============================================================================
# Target rules for targets named inclusion

# Build rule for target.
inclusion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 inclusion
.PHONY : inclusion

# fast build rule for target.
inclusion/fast:
	$(MAKE) $(MAKESILENT) -f experiments/CMakeFiles/inclusion.dir/build.make experiments/CMakeFiles/inclusion.dir/build
.PHONY : inclusion/fast

#=============================================================================
# Target rules for targets named constant

# Build rule for target.
constant: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 constant
.PHONY : constant

# fast build rule for target.
constant/fast:
	$(MAKE) $(MAKESILENT) -f experiments/CMakeFiles/constant.dir/build.make experiments/CMakeFiles/constant.dir/build
.PHONY : constant/fast

#=============================================================================
# Target rules for targets named measure-inclusion

# Build rule for target.
measure-inclusion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 measure-inclusion
.PHONY : measure-inclusion

# fast build rule for target.
measure-inclusion/fast:
	$(MAKE) $(MAKESILENT) -f experiments/CMakeFiles/measure-inclusion.dir/build.make experiments/CMakeFiles/measure-inclusion.dir/build
.PHONY : measure-inclusion/fast

#=============================================================================
# Target rules for targets named test-is-constant

# Build rule for target.
test-is-constant: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-is-constant
.PHONY : test-is-constant

# fast build rule for target.
test-is-constant/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-is-constant.dir/build.make tests/CMakeFiles/test-is-constant.dir/build
.PHONY : test-is-constant/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-inf-1state

# Build rule for target.
test-self-inclusion-rand-inf-1state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-inf-1state
.PHONY : test-self-inclusion-rand-inf-1state

# fast build rule for target.
test-self-inclusion-rand-inf-1state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-inf-1state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-inf-1state.dir/build
.PHONY : test-self-inclusion-rand-inf-1state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-inf-2state

# Build rule for target.
test-self-inclusion-rand-inf-2state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-inf-2state
.PHONY : test-self-inclusion-rand-inf-2state

# fast build rule for target.
test-self-inclusion-rand-inf-2state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-inf-2state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-inf-2state.dir/build
.PHONY : test-self-inclusion-rand-inf-2state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-inf-4state

# Build rule for target.
test-self-inclusion-rand-inf-4state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-inf-4state
.PHONY : test-self-inclusion-rand-inf-4state

# fast build rule for target.
test-self-inclusion-rand-inf-4state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-inf-4state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-inf-4state.dir/build
.PHONY : test-self-inclusion-rand-inf-4state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-inf-10state

# Build rule for target.
test-self-inclusion-rand-inf-10state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-inf-10state
.PHONY : test-self-inclusion-rand-inf-10state

# fast build rule for target.
test-self-inclusion-rand-inf-10state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-inf-10state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-inf-10state.dir/build
.PHONY : test-self-inclusion-rand-inf-10state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-inf-8state-4alph

# Build rule for target.
test-self-inclusion-rand-inf-8state-4alph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-inf-8state-4alph
.PHONY : test-self-inclusion-rand-inf-8state-4alph

# fast build rule for target.
test-self-inclusion-rand-inf-8state-4alph/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-inf-8state-4alph.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-inf-8state-4alph.dir/build
.PHONY : test-self-inclusion-rand-inf-8state-4alph/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-inf-1state

# Build rule for target.
test-inclusion-rand-inf-1state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-inf-1state
.PHONY : test-inclusion-rand-inf-1state

# fast build rule for target.
test-inclusion-rand-inf-1state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-inf-1state.dir/build.make tests/CMakeFiles/test-inclusion-rand-inf-1state.dir/build
.PHONY : test-inclusion-rand-inf-1state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-inf-2state

# Build rule for target.
test-inclusion-rand-inf-2state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-inf-2state
.PHONY : test-inclusion-rand-inf-2state

# fast build rule for target.
test-inclusion-rand-inf-2state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-inf-2state.dir/build.make tests/CMakeFiles/test-inclusion-rand-inf-2state.dir/build
.PHONY : test-inclusion-rand-inf-2state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-inf-4state

# Build rule for target.
test-inclusion-rand-inf-4state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-inf-4state
.PHONY : test-inclusion-rand-inf-4state

# fast build rule for target.
test-inclusion-rand-inf-4state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-inf-4state.dir/build.make tests/CMakeFiles/test-inclusion-rand-inf-4state.dir/build
.PHONY : test-inclusion-rand-inf-4state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-sup-1state

# Build rule for target.
test-self-inclusion-rand-sup-1state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-sup-1state
.PHONY : test-self-inclusion-rand-sup-1state

# fast build rule for target.
test-self-inclusion-rand-sup-1state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-sup-1state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-sup-1state.dir/build
.PHONY : test-self-inclusion-rand-sup-1state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-sup-2state

# Build rule for target.
test-self-inclusion-rand-sup-2state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-sup-2state
.PHONY : test-self-inclusion-rand-sup-2state

# fast build rule for target.
test-self-inclusion-rand-sup-2state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-sup-2state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-sup-2state.dir/build
.PHONY : test-self-inclusion-rand-sup-2state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-sup-4state

# Build rule for target.
test-self-inclusion-rand-sup-4state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-sup-4state
.PHONY : test-self-inclusion-rand-sup-4state

# fast build rule for target.
test-self-inclusion-rand-sup-4state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-sup-4state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-sup-4state.dir/build
.PHONY : test-self-inclusion-rand-sup-4state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-sup-10state

# Build rule for target.
test-self-inclusion-rand-sup-10state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-sup-10state
.PHONY : test-self-inclusion-rand-sup-10state

# fast build rule for target.
test-self-inclusion-rand-sup-10state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-sup-10state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-sup-10state.dir/build
.PHONY : test-self-inclusion-rand-sup-10state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-sup-8state-4alph

# Build rule for target.
test-self-inclusion-rand-sup-8state-4alph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-sup-8state-4alph
.PHONY : test-self-inclusion-rand-sup-8state-4alph

# fast build rule for target.
test-self-inclusion-rand-sup-8state-4alph/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-sup-8state-4alph.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-sup-8state-4alph.dir/build
.PHONY : test-self-inclusion-rand-sup-8state-4alph/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-sup-1state

# Build rule for target.
test-inclusion-rand-sup-1state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-sup-1state
.PHONY : test-inclusion-rand-sup-1state

# fast build rule for target.
test-inclusion-rand-sup-1state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-sup-1state.dir/build.make tests/CMakeFiles/test-inclusion-rand-sup-1state.dir/build
.PHONY : test-inclusion-rand-sup-1state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-sup-2state

# Build rule for target.
test-inclusion-rand-sup-2state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-sup-2state
.PHONY : test-inclusion-rand-sup-2state

# fast build rule for target.
test-inclusion-rand-sup-2state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-sup-2state.dir/build.make tests/CMakeFiles/test-inclusion-rand-sup-2state.dir/build
.PHONY : test-inclusion-rand-sup-2state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-sup-4state

# Build rule for target.
test-inclusion-rand-sup-4state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-sup-4state
.PHONY : test-inclusion-rand-sup-4state

# fast build rule for target.
test-inclusion-rand-sup-4state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-sup-4state.dir/build.make tests/CMakeFiles/test-inclusion-rand-sup-4state.dir/build
.PHONY : test-inclusion-rand-sup-4state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-sup-8state

# Build rule for target.
test-inclusion-rand-sup-8state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-sup-8state
.PHONY : test-inclusion-rand-sup-8state

# fast build rule for target.
test-inclusion-rand-sup-8state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-sup-8state.dir/build.make tests/CMakeFiles/test-inclusion-rand-sup-8state.dir/build
.PHONY : test-inclusion-rand-sup-8state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-limsup-1state

# Build rule for target.
test-self-inclusion-rand-limsup-1state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-limsup-1state
.PHONY : test-self-inclusion-rand-limsup-1state

# fast build rule for target.
test-self-inclusion-rand-limsup-1state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-limsup-1state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-limsup-1state.dir/build
.PHONY : test-self-inclusion-rand-limsup-1state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-limsup-2state

# Build rule for target.
test-self-inclusion-rand-limsup-2state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-limsup-2state
.PHONY : test-self-inclusion-rand-limsup-2state

# fast build rule for target.
test-self-inclusion-rand-limsup-2state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-limsup-2state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-limsup-2state.dir/build
.PHONY : test-self-inclusion-rand-limsup-2state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-limsup-4state

# Build rule for target.
test-self-inclusion-rand-limsup-4state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-limsup-4state
.PHONY : test-self-inclusion-rand-limsup-4state

# fast build rule for target.
test-self-inclusion-rand-limsup-4state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-limsup-4state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-limsup-4state.dir/build
.PHONY : test-self-inclusion-rand-limsup-4state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-limsup-10state

# Build rule for target.
test-self-inclusion-rand-limsup-10state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-limsup-10state
.PHONY : test-self-inclusion-rand-limsup-10state

# fast build rule for target.
test-self-inclusion-rand-limsup-10state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-limsup-10state.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-limsup-10state.dir/build
.PHONY : test-self-inclusion-rand-limsup-10state/fast

#=============================================================================
# Target rules for targets named test-self-inclusion-rand-limsup-8state-4alph

# Build rule for target.
test-self-inclusion-rand-limsup-8state-4alph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-self-inclusion-rand-limsup-8state-4alph
.PHONY : test-self-inclusion-rand-limsup-8state-4alph

# fast build rule for target.
test-self-inclusion-rand-limsup-8state-4alph/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-self-inclusion-rand-limsup-8state-4alph.dir/build.make tests/CMakeFiles/test-self-inclusion-rand-limsup-8state-4alph.dir/build
.PHONY : test-self-inclusion-rand-limsup-8state-4alph/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-limsup-1state

# Build rule for target.
test-inclusion-rand-limsup-1state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-limsup-1state
.PHONY : test-inclusion-rand-limsup-1state

# fast build rule for target.
test-inclusion-rand-limsup-1state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-limsup-1state.dir/build.make tests/CMakeFiles/test-inclusion-rand-limsup-1state.dir/build
.PHONY : test-inclusion-rand-limsup-1state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-limsup-2state

# Build rule for target.
test-inclusion-rand-limsup-2state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-limsup-2state
.PHONY : test-inclusion-rand-limsup-2state

# fast build rule for target.
test-inclusion-rand-limsup-2state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-limsup-2state.dir/build.make tests/CMakeFiles/test-inclusion-rand-limsup-2state.dir/build
.PHONY : test-inclusion-rand-limsup-2state/fast

#=============================================================================
# Target rules for targets named test-inclusion-rand-limsup-4state

# Build rule for target.
test-inclusion-rand-limsup-4state: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inclusion-rand-limsup-4state
.PHONY : test-inclusion-rand-limsup-4state

# fast build rule for target.
test-inclusion-rand-limsup-4state/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-inclusion-rand-limsup-4state.dir/build.make tests/CMakeFiles/test-inclusion-rand-limsup-4state.dir/build
.PHONY : test-inclusion-rand-limsup-4state/fast

src/quak-main.o: src/quak-main.cpp.o
.PHONY : src/quak-main.o

# target to build an object file
src/quak-main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakbin.dir/build.make CMakeFiles/quakbin.dir/src/quak-main.cpp.o
.PHONY : src/quak-main.cpp.o

src/quak-main.i: src/quak-main.cpp.i
.PHONY : src/quak-main.i

# target to preprocess a source file
src/quak-main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakbin.dir/build.make CMakeFiles/quakbin.dir/src/quak-main.cpp.i
.PHONY : src/quak-main.cpp.i

src/quak-main.s: src/quak-main.cpp.s
.PHONY : src/quak-main.s

# target to generate assembly for a file
src/quak-main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quakbin.dir/build.make CMakeFiles/quakbin.dir/src/quak-main.cpp.s
.PHONY : src/quak-main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... constant"
	@echo "... inclusion"
	@echo "... measure-inclusion"
	@echo "... quak"
	@echo "... quak-private"
	@echo "... quakbin"
	@echo "... quakso"
	@echo "... test-inclusion-rand-inf-1state"
	@echo "... test-inclusion-rand-inf-2state"
	@echo "... test-inclusion-rand-inf-4state"
	@echo "... test-inclusion-rand-limsup-1state"
	@echo "... test-inclusion-rand-limsup-2state"
	@echo "... test-inclusion-rand-limsup-4state"
	@echo "... test-inclusion-rand-sup-1state"
	@echo "... test-inclusion-rand-sup-2state"
	@echo "... test-inclusion-rand-sup-4state"
	@echo "... test-inclusion-rand-sup-8state"
	@echo "... test-is-constant"
	@echo "... test-self-inclusion-rand-inf-10state"
	@echo "... test-self-inclusion-rand-inf-1state"
	@echo "... test-self-inclusion-rand-inf-2state"
	@echo "... test-self-inclusion-rand-inf-4state"
	@echo "... test-self-inclusion-rand-inf-8state-4alph"
	@echo "... test-self-inclusion-rand-limsup-10state"
	@echo "... test-self-inclusion-rand-limsup-1state"
	@echo "... test-self-inclusion-rand-limsup-2state"
	@echo "... test-self-inclusion-rand-limsup-4state"
	@echo "... test-self-inclusion-rand-limsup-8state-4alph"
	@echo "... test-self-inclusion-rand-sup-10state"
	@echo "... test-self-inclusion-rand-sup-1state"
	@echo "... test-self-inclusion-rand-sup-2state"
	@echo "... test-self-inclusion-rand-sup-4state"
	@echo "... test-self-inclusion-rand-sup-8state-4alph"
	@echo "... src/quak-main.o"
	@echo "... src/quak-main.i"
	@echo "... src/quak-main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

