# CMake generated Testfile for 
# Source directory: /Users/h4kcrun/Repos/QuAK/tests
# Build directory: /Users/h4kcrun/Repos/QuAK/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-is-constant "test-is-constant")
set_tests_properties(test-is-constant PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;22;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-inf-1state "test-self-inclusion-rand-inf-1state")
set_tests_properties(test-self-inclusion-rand-inf-1state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;41;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-inf-2state "test-self-inclusion-rand-inf-2state")
set_tests_properties(test-self-inclusion-rand-inf-2state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;53;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-inf-4state "test-self-inclusion-rand-inf-4state")
set_tests_properties(test-self-inclusion-rand-inf-4state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;65;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-inf-10state "test-self-inclusion-rand-inf-10state")
set_tests_properties(test-self-inclusion-rand-inf-10state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;78;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-inf-8state-4alph "test-self-inclusion-rand-inf-8state-4alph")
set_tests_properties(test-self-inclusion-rand-inf-8state-4alph PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;90;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-inf-1state "test-inclusion-rand-inf-1state")
set_tests_properties(test-inclusion-rand-inf-1state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;102;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-inf-2state "test-inclusion-rand-inf-2state")
set_tests_properties(test-inclusion-rand-inf-2state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;115;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-inf-4state "test-inclusion-rand-inf-4state")
set_tests_properties(test-inclusion-rand-inf-4state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;128;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-sup-1state "test-self-inclusion-rand-sup-1state")
set_tests_properties(test-self-inclusion-rand-sup-1state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;146;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-sup-2state "test-self-inclusion-rand-sup-2state")
set_tests_properties(test-self-inclusion-rand-sup-2state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;158;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-sup-4state "test-self-inclusion-rand-sup-4state")
set_tests_properties(test-self-inclusion-rand-sup-4state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;170;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-sup-10state "test-self-inclusion-rand-sup-10state")
set_tests_properties(test-self-inclusion-rand-sup-10state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;182;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-sup-8state-4alph "test-self-inclusion-rand-sup-8state-4alph")
set_tests_properties(test-self-inclusion-rand-sup-8state-4alph PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;194;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-sup-1state "test-inclusion-rand-sup-1state")
set_tests_properties(test-inclusion-rand-sup-1state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;206;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-sup-2state "test-inclusion-rand-sup-2state")
set_tests_properties(test-inclusion-rand-sup-2state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;218;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-sup-4state "test-inclusion-rand-sup-4state")
set_tests_properties(test-inclusion-rand-sup-4state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;230;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-sup-8state "test-inclusion-rand-sup-8state")
set_tests_properties(test-inclusion-rand-sup-8state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;243;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-limsup-1state "test-self-inclusion-rand-limsup-1state")
set_tests_properties(test-self-inclusion-rand-limsup-1state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;262;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-limsup-2state "test-self-inclusion-rand-limsup-2state")
set_tests_properties(test-self-inclusion-rand-limsup-2state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;274;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-limsup-4state "test-self-inclusion-rand-limsup-4state")
set_tests_properties(test-self-inclusion-rand-limsup-4state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;286;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-limsup-10state "test-self-inclusion-rand-limsup-10state")
set_tests_properties(test-self-inclusion-rand-limsup-10state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;298;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-self-inclusion-rand-limsup-8state-4alph "test-self-inclusion-rand-limsup-8state-4alph")
set_tests_properties(test-self-inclusion-rand-limsup-8state-4alph PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;7;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;310;add_self_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-limsup-1state "test-inclusion-rand-limsup-1state")
set_tests_properties(test-inclusion-rand-limsup-1state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;322;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-limsup-2state "test-inclusion-rand-limsup-2state")
set_tests_properties(test-inclusion-rand-limsup-2state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;334;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
add_test(test-inclusion-rand-limsup-4state "test-inclusion-rand-limsup-4state")
set_tests_properties(test-inclusion-rand-limsup-4state PROPERTIES  _BACKTRACE_TRIPLES "/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;15;add_test;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;346;add_exe;/Users/h4kcrun/Repos/QuAK/tests/CMakeLists.txt;0;")
